@TestJsonPatch_HostAddress = http://localhost:5243

###

GET {{TestJsonPatch_HostAddress}}/codesets/1

###

POST {{TestJsonPatch_HostAddress}}/codesets/string
Content-Type: application/json

{
  "id": "1",
  "name": "Sample CodeSet",
  "codes": [
    {
      "codeId": 101,
      "codeName": "Code1"
    },
    {
      "codeId": 102,
      "codeName": "Code2",
      "codeDescription": "Description for Code2"
    }
  ]
}

###

PATCH {{TestJsonPatch_HostAddress}}/codesets/1
Content-Type: application/json-patch+json

[
  { "op": "replace", "path": "/name", "value": "Updated CodeSet" },
]

###

PATCH {{TestJsonPatch_HostAddress}}/codesets/1
Content-Type: application/json-patch+json

[
  { "op": "remove", "path": "/codes/id1"},
]

###

PATCH {{TestJsonPatch_HostAddress}}/codesets/1
Content-Type: application/json-patch+json

[
  { "op": "replace", "path": "/codes/id2/codeType", "value": "type3"},
]

###

PATCH {{TestJsonPatch_HostAddress}}/codesets/1
Content-Type: application/json-patch+json

[
  { "op": "add", "path": "/codes/id5", "value": { "codeName": "Code3", "codeType": "NewType" } }
]
###
